name = "QuasiHarmonicApproximation"
uuid = "0a5e5b10-f605-11e8-2788-b7908c05924e"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
OptionalArgChecks = "dfbeeb84-381a-44da-9ec9-a723abf299c7"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Setfield = "0.3, 0.4, 0.5, 0.6"
Unitful = "0.18, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
