name = "QuasiHarmonicApprox"
uuid = "ad1dadc2-b711-4cea-a890-68b28ba296e8"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
DiffEqOperators = "9fdde737-9c7f-55bf-ade8-46b3f136cc48"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
EquationsOfStateOfSolids = "1eaa2786-f833-4167-8397-974edad0881e"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
OptionalArgChecks = "dfbeeb84-381a-44da-9ec9-a723abf299c7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DiffEqOperators = "4.23"
DimensionalData = "0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20"
EquationsOfStateOfSolids = "0.2, 0.3, 0.4"
Interpolations = "0.13"
OptionalArgChecks = "0.3"
Unitful = "0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
