name = "QuasiHarmonicApproximation"
uuid = "0a5e5b10-f605-11e8-2788-b7908c05924e"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
EquationsOfState = "0438fec6-b81c-52d9-9651-d286848f50a8"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Rematch = "bfecab0d-fd4d-5014-a23f-56c5fae6447a"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
