name = "QuasiHarmonicApproximation"
uuid = "0a5e5b10-f605-11e8-2788-b7908c05924e"
authors = ["Qi Zhang <singularitti@outlook.com>"]
version = "0.1.0"

[deps]
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
UnitfulAtomic = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
